name: Deploy-To-Prod

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Bot Repo
        uses: fifsky/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          user: ${{secrets.SSH_USER}}
          command: |
            if [ -d /root/re-bots ]; then cd /root/re-bots && git fetch --all && git reset --hard origin/master ; else git clone git@github.com:vchitepu/re-bots.git; fi
            JOKER_BOT_SECRET=${{secrets.JOKER_BOT_SECRET}}
            CYPTO_BOT_SECRET=${{secrets.CRYPTO_BOT_SECRET}}
            pip3 install -r requirements.txt
            echo "Deployment successful to server"
            pm2 delete all
            pm2 start /root/re-bots/bots/joker-bot/jokerbot.py --name jokerbot --interpreter /usr/bin/python3
            pm2 start /root/re-bots/bots/crypto-bot/cryptobot.py --name cryptobot --interpreter /usr/bin/python3
            echo "Started JokerBot"


