name: Deploy-To-Prod

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Bot Repo
        uses: fifsky/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          user: ${{secrets.SSH_USER}}
          command: |
            if [ -d /root/re-bots ]; then cd /root/re-bots && git pull ; else git@github.com:vchitepu/re-bots.git; fi
            echo "Deployment successful to server"
